"""empty message

Revision ID: 617ae4bb394e
Revises: 
Create Date: 2023-07-18 12:02:30.540075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617ae4bb394e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=True),
    sa.Column('alt_1', sa.String(), nullable=True),
    sa.Column('alt_2', sa.String(), nullable=True),
    sa.Column('alt_3', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('percentage_correct', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['Quizzes.id'], name=op.f('fk_Questions_quiz_id_Quizzes')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['Quizzes.id'], name=op.f('fk_Results_quiz_id_Quizzes')),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name=op.f('fk_Results_user_id_Users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Results')
    op.drop_table('Questions')
    op.drop_table('Users')
    op.drop_table('Quizzes')
    # ### end Alembic commands ###
